---
hero_image: images/banner.png
theme: red
duration: 1
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Green Your City
description: Control your toy helicopter to water flowers in a city.
original_url: https://codeclubprojects.org/en-GB/scratch/green-your-city
interests: ''
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: Introduction
- title: Helicopter
- title: 'Challenge: Animate your helicopter'
- title: Water
- title: 'Challenge: Too much water'
- title: Flowers
- title: 'Challenge: Keeping score'
- title: 'Challenge: Floating flowers'

