---
hero_image: images/green-your-city.png
theme: green
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Green Your City
description: Control your toy helicopter to water flowers in a city.
original_url: https://codeclubprojects.org/en-GB/scratch/green-your-city
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
  completion: engaged
- title: Helicopter
- title: 'Challenge: Animate your helicopter'
- title: Water
- title: 'Challenge: Too much water'
- title: Flowers
- title: 'Challenge: Keeping score'
  completion: internal
- title: 'Challenge: Floating flowers'
