---
hero_image: images/green-your-city.png
theme: green
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: "Gwyrddio'r Ddinas"
description: Rheola hofrennydd i roi dŵr i flodau yn y ddinas.
original_url: https://codeclubprojects.org/en-GB/scratch/green-your-city
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps: 
- title: Cyflwyniad
- title: Hofrennydd
- title: 'Her: Animeiddio dy hofrennydd'
- title: Dŵr
- title: 'Her: Gormod o ddŵr'
- title: Blodau
- title: 'Her: Cadw sgôr'
- title: 'Her: Blodau yn arnofio'